blank_issues_enabled: false
contact_links:
  - name: Ueberauth Slack Channel
    url: https://elixir-lang.slack.com/archives/C0ETJ9081
    about: Our Elixir Slack Channel.
  - name: Ueberauth Discussions
    url: https://github.com/ueberauth/ueberauth/discussions
    about: Ask questions and discuss ideas around Ueberauth.
  - name: Guardian Discussions
    url: https://github.com/ueberauth/guardian/discussions
    about: Ask questions and discuss ideas around Guardian.
